name: Belajar CI/CD Python

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build:
    needs: install  # Build hanya berjalan jika install selesai sukses
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Build Docker image
        run: |
          docker build -t docker/coba .
  
      - name: Tag Docker image
        run: |
          docker tag docker/coba:latest 830108781204.dkr.ecr.us-west-2.amazonaws.com/docker/coba:latest
  
      - name: Push Docker image to ECR
        run: |
          docker push 830108781204.dkr.ecr.us-west-2.amazonaws.com/docker/coba:latest

  deploy:
    needs: build  # Deploy hanya berjalan jika build selesai sukses
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.EB_APP_NAME }} \
            --version-label ${{ github.sha }} \
            --auto-create-application \
            --docker-image-name ${{ secrets.ECR_REGISTRY }}/docker/coba:${{ github.sha }}
          
          aws elasticbeanstalk update-environment \
            --environment-name ${{ secrets.EB_ENV_NAME }} \
            --version-label ${{ github.sha }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EB_APP_NAME: ${{ secrets.EB_APP_NAME }}
          EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}

      - name: Check Elastic Beanstalk Health Status
        run: |
          echo "Checking the health of the Elastic Beanstalk environment..."
          aws elasticbeanstalk describe-environment-health \
            --environment-name ${{ secrets.EB_ENV_NAME }} \
            --attribute HealthStatus \
            --query "HealthStatus"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}