name: Belajar CI/CD Python

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build:
    needs: install  # Build hanya berjalan jika install selesai sukses
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Build Docker image
        run: |
          docker build -t docker/coba .
  
      - name: Tag Docker image
        run: |
          docker tag docker/coba:latest 830108781204.dkr.ecr.us-west-2.amazonaws.com/docker/coba:latest
  
      - name: Push Docker image to ECR
        run: |
          docker push 830108781204.dkr.ecr.us-west-2.amazonaws.com/docker/coba:latest

  deploy:
    needs: build  # Deploy hanya berjalan jika build selesai sukses
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk describe-application-versions --application-name ${{ secrets.EB_APP_NAME }}
      
        aws elasticbeanstalk update-environment \
          --environment-name ${{ secrets.EB_ENV_NAME }} \
          --version-label 37be4dabf631d09884d8559f5547673d9554b9af \
          --option-settings "Namespace=aws:elasticbeanstalk:container:docker,OptionName=Image,Value=830108781204.dkr.ecr.us-west-2.amazonaws.com/docker/coba:latest"
            
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}
        EB_APP_NAME: ${{ secrets.EB_APP_NAME }}