name: Belajar CICD Python 

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip3 install --upgrade pip3
          pip3 install -r requirements.txt

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          docker build -t apps .

      - name: image Docker to .zip
        run: |
        zip -r apps.zip

      - name: upload file .zip ke AWS S#
        run: |
          aws cp apps.zip s3://${{ secrets.S3_BUCKET_NAME }}/apps.zip
        env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        AWS_REGION: ${{ secrets.AWS_REGION }}        

         